name: CI

on:
  pull_request:
  push:
    branches: [main]
jobs:
  test-qgis:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: "latest"
      - name: Generate resources.py
        run: pixi run pbt compile
      - name: Run tests
        env:
          DISPLAY: :99
        run: >
          xvfb-run -s '+extension GLX -screen 0 1024x768x24'
          pixi run tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
