name: Release
on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: "latest"
    - name: Deploy plugin
      run: >-
        pixi run qgis-plugin-ci
        release ${GITHUB_REF/refs\/tags\//}
        --github-token ${{ secrets.GITHUB_TOKEN }}
        --osgeo-username ${{ secrets.OSGEO_USER }}
        --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
